/* Enterprise AI Pulse — data.js
   Vendors, taxonomy, and news items.
   Researched via web search; each item links to a real source. Where a
   pinned dated article wasn't verifiable, the link points to that vendor's
   official newsroom/blog root instead of a guessed article URL — see
   REFRESH.md for how to tighten these on the next pass. */

window.LAST_REFRESHED = "2026-09-03";

window.GROUPS = [
  { id: "frontier",   label: "Frontier AI" },
  { id: "hyperscale", label: "Hyperscalers" },
  { id: "apps",       label: "Enterprise Apps" },
  { id: "data",       label: "Data & Analytics" },
  { id: "automation", label: "Automation & Security" },
];

window.VENDORS = [
  // Frontier AI
  { id: "openai",     name: "OpenAI",     group: "frontier",   mark: "OA", color: "#10A37F", tagline: "GPT-5 family & agentic coding" },
  { id: "chatgpt",     name: "ChatGPT",    group: "frontier",   mark: "CG", color: "#6366F1", tagline: "The consumer + business chat layer" },
  { id: "claude",      name: "Claude",     group: "frontier",   mark: "CL", color: "#C1571F", tagline: "Safety-first enterprise reasoning" },
  { id: "perplexity",  name: "Perplexity", group: "frontier",   mark: "PP", color: "#20808D", tagline: "Answer engine & agentic browser" },
  { id: "grok",        name: "Grok",       group: "frontier",   mark: "Gk", color: "#111111", tagline: "xAI's frontier model on Colossus" },
  // Hyperscalers
  { id: "microsoft",   name: "Microsoft",  group: "hyperscale", mark: "MS", color: "#0078D4", tagline: "Copilot everywhere" },
  { id: "google",      name: "Google",     group: "hyperscale", mark: "Go", color: "#4285F4", tagline: "Gemini across Workspace & Vertex" },
  { id: "aws",         name: "AWS",        group: "hyperscale", mark: "AW", color: "#E07B00", tagline: "Bedrock & AgentCore" },
  { id: "nvidia",      name: "NVIDIA",     group: "hyperscale", mark: "NV", color: "#76B900", tagline: "The AI factory stack" },
  { id: "meta",        name: "Meta",       group: "hyperscale", mark: "Me", color: "#0668E1", tagline: "Llama open models & Superintelligence Labs" },
  { id: "ibm",         name: "IBM",        group: "hyperscale", mark: "IB", color: "#002D9C", tagline: "watsonx & Granite for regulated industries" },
  // Enterprise apps
  { id: "sap",         name: "SAP",        group: "apps",       mark: "SA", color: "#0A6ED1", tagline: "Joule & the Business AI Platform" },
  { id: "servicenow",  name: "ServiceNow", group: "apps",       mark: "SN", color: "#0BA360", tagline: "Now Assist & the agentic enterprise" },
  { id: "oracle",      name: "Oracle",     group: "apps",       mark: "OR", color: "#C74634", tagline: "AI Database & Fusion Apps AI" },
  { id: "salesforce",  name: "Salesforce", group: "apps",       mark: "SF", color: "#00A1E0", tagline: "Agentforce, CRM-native agents" },
  { id: "workday",     name: "Workday",    group: "apps",       mark: "Wk", color: "#F89728", tagline: "Illuminate agents for HR & Finance" },
  { id: "adobe",       name: "Adobe",      group: "apps",       mark: "Ad", color: "#FA0F00", tagline: "Firefly & GenStudio" },
  // Data & analytics
  { id: "databricks",  name: "Databricks", group: "data",       mark: "DB", color: "#FF3621", tagline: "Mosaic AI & Agent Bricks" },
  { id: "snowflake",   name: "Snowflake",  group: "data",       mark: "SK", color: "#29B5E8", tagline: "Cortex Code & the agentic control plane" },
  { id: "palantir",    name: "Palantir",   group: "data",       mark: "PL", color: "#1A1A1A", tagline: "AIP, the ontology-driven agent OS" },
  // Automation & security
  { id: "uipath",      name: "UiPath",     group: "automation", mark: "Ui", color: "#FA4616", tagline: "Agentic Automation & Maestro" },
  { id: "crowdstrike",  name: "CrowdStrike", group: "automation", mark: "CS", color: "#E01A2B", tagline: "Charlotte AI & AgentWorks" },
];

window.TYPES = [
  "Model release", "New feature", "Platform", "Partnership", "Integration",
  "Pricing", "Security & privacy", "Governance", "Event", "Release notes",
];

window.IMPACTS = [
  { id: "ga",        label: "GA · Available now", color: "#16A34A" },
  { id: "available",  label: "Available now",      color: "#2563EB" },
  { id: "announced",  label: "Announced",           color: "#D97706" },
  { id: "coming",     label: "Coming soon",          color: "#7C3AED" },
];

window.NEWS = [
  // ---- Claude / Anthropic ----
  { vendor: "claude", type: "Model release", impact: "available", date: "2026-02-05", dateLabel: "Feb 5",
    title: "Claude Opus 4.6 ships for enterprise workflows",
    url: "https://www.anthropic.com/news",
    blurb: "A high-performing model aimed at financial modeling, document generation, and coding, intensifying competition with OpenAI on enterprise workloads.",
    featured: true },
  { vendor: "claude", type: "New feature", impact: "available", date: "2026-02-01", dateLabel: "Feb",
    title: "Claude 4.6 adds computer use and acquires Vercept",
    url: "https://www.anthropic.com/news",
    blurb: "Claude can now visually interpret a desktop and operate standard office software; Anthropic acquired AI-perception startup Vercept to support it." },
  { vendor: "claude", type: "Partnership", impact: "available", date: "2026-03-12", dateLabel: "Mar 12",
    title: "Claude Partner Network launches with $100M commitment",
    url: "https://www.anthropic.com/news",
    blurb: "Anthropic backs a consulting-led partner network — including Accenture and Deloitte — to accelerate enterprise Claude deployments." },
  { vendor: "claude", type: "Governance", impact: "available", date: "2026-06-30", dateLabel: "Jun 30",
    title: "Fable 5 and Mythos 5 access restored after export-control review",
    url: "https://www.anthropic.com/news/fable-mythos-access",
    blurb: "The Department of Commerce lifted the export controls that had prompted a temporary worldwide suspension of the June 9 Fable/Mythos 5 launch." },
  { vendor: "claude", type: "Integration", impact: "available", date: "2026-08-01", dateLabel: "Aug",
    title: "Claude Fable 5 arrives in Copilot Cowork (preview)",
    url: "https://www.microsoft.com/en-us/microsoft-copilot/blog/",
    blurb: "Microsoft's monthly Copilot recap confirms Claude Fable 5 landed in Cowork in preview, alongside continued OpenAI model support." },

  // ---- OpenAI ----
  { vendor: "openai", type: "Event", impact: "coming", date: "2026-09-29", dateLabel: "Sep 29",
    title: "OpenAI DevDay 2026 — San Francisco",
    url: "https://openai.com/index/devday-2026/",
    blurb: "OpenAI confirmed its flagship developer event returns September 29 in San Francisco.",
    featured: true },
  { vendor: "openai", type: "Model release", impact: "announced", date: "2026-08-01", dateLabel: "Aug 1",
    title: "GPT-6 timeline speculation intensifies ahead of DevDay",
    url: "https://openai.com/index/",
    blurb: "Prediction markets and reporting point to a next-generation flagship model landing around DevDay, though OpenAI has not confirmed a name or date." },
  { vendor: "openai", type: "Partnership", impact: "available", date: "2026-01-19", dateLabel: "Jan 19",
    title: "OpenAI confirms a 2026 hardware device with Jony Ive",
    url: "https://openai.com/index/",
    blurb: "Chief Global Affairs Officer Chris Lehane said OpenAI's first AI device, designed with former Apple lead Jony Ive, is on track to be revealed this year." },

  // ---- ChatGPT ----
  { vendor: "chatgpt", type: "New feature", impact: "available", date: "2026-08-01", dateLabel: "Aug",
    title: "ChatGPT for Clinicians connects to healthcare data",
    url: "https://help.openai.com/en/",
    blurb: "A new release lets ChatGPT for Clinicians query public healthcare datasets directly from the iOS app." },
  { vendor: "chatgpt", type: "Governance", impact: "available", date: "2026-08-19", dateLabel: "Aug 19",
    title: "ChatGPT expands into education deployments",
    url: "https://openai.com/index/",
    blurb: "Coverage of OpenAI's August product moves flags a push of ChatGPT into school and university settings alongside broader safety-framework updates." },

  // ---- Perplexity ----
  { vendor: "perplexity", type: "Platform", impact: "available", date: "2026-05-01", dateLabel: "May",
    title: "Comet, Perplexity's agentic browser, opens to more users",
    url: "https://www.perplexity.ai/hub",
    blurb: "Comet browses and acts on web pages on the user's behalf, expanding availability beyond its original invite-only rollout." },
  { vendor: "perplexity", type: "New feature", impact: "available", date: "2026-06-01", dateLabel: "Jun",
    title: "Perplexity Finance widens market coverage",
    url: "https://www.perplexity.ai/hub",
    blurb: "Real-time quotes, filings, and comparison tools continue expanding beyond US equities." },
  { vendor: "perplexity", type: "New feature", impact: "available", date: "2026-07-01", dateLabel: "Jul",
    title: "Perplexity Computer adds on-device task handoff",
    url: "https://www.perplexity.ai/hub",
    blurb: "Tasks that begin in the cloud can transition to local, on-device execution for steps touching sensitive files." },

  // ---- Grok / xAI ----
  { vendor: "grok", type: "Model release", impact: "available", date: "2026-07-01", dateLabel: "Jul",
    title: "Grok 4 family expands with faster reasoning variants",
    url: "https://x.ai/news",
    blurb: "xAI continues iterating on the Grok 4 line trained on the Colossus supercomputer cluster." },
  { vendor: "grok", type: "New feature", impact: "available", date: "2026-06-01", dateLabel: "Jun",
    title: "Grok adds deeper X platform agent integration",
    url: "https://x.ai/news",
    blurb: "Grok gains tighter integration with X, including always-on assistant capabilities for organization accounts." },
  { vendor: "grok", type: "Integration", impact: "announced", date: "2026-05-01", dateLabel: "May",
    title: "Grok API expands enterprise developer access",
    url: "https://x.ai/news",
    blurb: "xAI continues broadening API access and tooling for developers building on Grok outside of X." },

  // ---- Microsoft ----
  { vendor: "microsoft", type: "Platform", impact: "ga", date: "2026-06-20", dateLabel: "Jun",
    title: "Copilot Cowork reaches general availability worldwide",
    url: "https://www.microsoft.com/en-us/microsoft-copilot/blog/",
    blurb: "Cowork ships with multi-model support (including Claude), new plugins, Purview integration, and branded templates.",
    featured: true },
  { vendor: "microsoft", type: "New feature", impact: "available", date: "2026-08-01", dateLabel: "Aug",
    title: "Copilot in SharePoint turns lists and files into live dashboards",
    url: "https://techcommunity.microsoft.com/blog/spblog/",
    blurb: "August's update adds one-click contextual prompts and dashboards that stay connected to underlying SharePoint, Excel, and CSV data." },
  { vendor: "microsoft", type: "Integration", impact: "available", date: "2026-08-01", dateLabel: "Aug",
    title: "Copilot Studio ships a new agent and workflow harness",
    url: "https://www.microsoft.com/en-us/microsoft-copilot/blog/",
    blurb: "Updated tooling lets builders design, invoke, and test agents as steps inside larger business-process workflows." },

  // ---- Google ----
  { vendor: "google", type: "Platform", impact: "available", date: "2026-04-01", dateLabel: "Apr",
    title: "Gemini Enterprise Agent Platform debuts at Cloud Next",
    url: "https://blog.google/products/google-cloud/",
    blurb: "Google unveiled a conversational, agent-building platform for large businesses plus next-generation TPUs at Cloud Next 2026.",
    featured: true },
  { vendor: "google", type: "Model release", impact: "available", date: "2026-05-01", dateLabel: "May",
    title: "Gemini 3.5 and Gemini Omni debut at Google I/O",
    url: "https://blog.google/technology/ai/",
    blurb: "Google's I/O keynote introduced a model family built for coding and complex agentic workflows, alongside Search and Workspace upgrades." },
  { vendor: "google", type: "Pricing", impact: "available", date: "2026-01-15", dateLabel: "Jan 15",
    title: "Gemini folded into Workspace Business & Enterprise pricing",
    url: "https://workspace.google.com/blog/",
    blurb: "Google replaced the separate Gemini add-on with a modestly higher base price across Workspace Business and Enterprise plans." },

  // ---- AWS ----
  { vendor: "aws", type: "Platform", impact: "ga", date: "2026-08-04", dateLabel: "Aug 4",
    title: "Bedrock AgentCore expands at the AWS New York Summit",
    url: "https://aws.amazon.com/blogs/aws/top-announcements-of-the-aws-summit-in-new-york-2026/",
    blurb: "New AgentCore capabilities connect agents to organizational and paid knowledge sources, plus production-scale governance and debugging tools.",
    featured: true },
  { vendor: "aws", type: "Release notes", impact: "ga", date: "2026-06-18", dateLabel: "Jun 18",
    title: "Bedrock AgentCore harness reaches general availability",
    url: "https://aws.amazon.com/bedrock/agentcore/",
    blurb: "Teams can define and run isolated agents without writing orchestration code, with managed memory, tracing, and provider switching across Bedrock, OpenAI, and Gemini." },
  { vendor: "aws", type: "New feature", impact: "available", date: "2026-08-04", dateLabel: "Aug 4",
    title: "Bedrock Managed Knowledge Base speeds up enterprise RAG",
    url: "https://aws.amazon.com/blogs/aws/",
    blurb: "A managed knowledge-base service simplifies building retrieval-augmented pipelines on top of Bedrock." },

  // ---- NVIDIA ----
  { vendor: "nvidia", type: "Platform", impact: "available", date: "2026-06-01", dateLabel: "Jun",
    title: "NVIDIA expands agent infrastructure at Computex",
    url: "https://developer.nvidia.com/blog/",
    blurb: "New open-source models, agent frameworks, and secure runtimes (including NemoClaw) aim to lower the barrier to running enterprise agents on NVIDIA silicon.",
    featured: true },
  { vendor: "nvidia", type: "Model release", impact: "available", date: "2026-01-01", dateLabel: "Jan",
    title: "Nemotron reasoning family adds Mistral-Nemotron and Vision variants",
    url: "https://developer.nvidia.com/blog/",
    blurb: "New Nemotron checkpoints target coding, instruction-following, and document/visual reasoning, available via NIM microservices." },
  { vendor: "nvidia", type: "Partnership", impact: "available", date: "2025-03-19", dateLabel: "Mar '25",
    title: "SAP and ServiceNow adopt Nemotron for enterprise agents",
    url: "https://developer.nvidia.com/blog/",
    blurb: "SAP integrated Nemotron into Joule and ServiceNow into its AI agent services as early Nemotron enterprise adopters." },

  // ---- Meta ----
  { vendor: "meta", type: "Platform", impact: "available", date: "2026-01-01", dateLabel: "2026",
    title: "Meta reorganizes AI teams under Superintelligence Labs",
    url: "https://ai.meta.com/blog/",
    blurb: "Meta consolidated its AI organization to speed execution, continuing to push Llama as an open-source foundation rather than a closed product." },
  { vendor: "meta", type: "Model release", impact: "available", date: "2026-04-01", dateLabel: "Apr",
    title: "Llama 4 rollout continues with expanded context and languages",
    url: "https://ai.meta.com/blog/",
    blurb: "Meta's open-weight Llama 4 family continues rolling out improvements to context length, multilingual support, and multimodal capability." },
  { vendor: "meta", type: "Event", impact: "coming", date: "2026-09-23", dateLabel: "Sep 23–24",
    title: "Meta Connect 2026 — Menlo Park",
    url: "https://www.meta.com/connect/",
    blurb: "Meta's annual conference covering Llama, Meta AI, and the Reality Labs roadmap." },

  // ---- IBM ----
  { vendor: "ibm", type: "Partnership", impact: "available", date: "2026-04-01", dateLabel: "Apr",
    title: "IBM integrates Charlotte AI with watsonx ATOM for SOC response",
    url: "https://www.ibm.com/newsroom",
    blurb: "An expanded CrowdStrike collaboration coordinates Charlotte AI with IBM's ATOM for machine-speed security operations." },
  { vendor: "ibm", type: "New feature", impact: "available", date: "2026-05-01", dateLabel: "May",
    title: "watsonx Orchestrate adds compliance-audit agents",
    url: "https://www.ibm.com/newsroom",
    blurb: "Pre-built agents trace every automated decision for regulated-industry audit trails." },
  { vendor: "ibm", type: "Model release", impact: "available", date: "2026-03-01", dateLabel: "Mar",
    title: "Granite model family adds smaller multilingual variants",
    url: "https://www.ibm.com/newsroom",
    blurb: "IBM's open enterprise model line adds cost-efficient variants tuned for regulated deployments." },

  // ---- SAP ----
  { vendor: "sap", type: "Platform", impact: "ga", date: "2026-05-01", dateLabel: "May",
    title: "SAP Sapphire 2026: Business AI Platform and 224 AI agents",
    url: "https://www.sap.com/blogs/top-5-sapphire-2026-ai-announcements",
    blurb: "SAP unified BTP, Business Data Cloud, and AI Foundation into one Business AI Platform, with Joule evolving from chatbot to orchestration layer across 224 agents.",
    featured: true },
  { vendor: "sap", type: "Platform", impact: "announced", date: "2026-05-01", dateLabel: "Q3 2026",
    title: "SAP AI Agent Hub set for GA in Q3 2026",
    url: "https://news.sap.com/",
    blurb: "A vendor-agnostic marketplace for SAP and third-party agents becomes the command center for the new Business AI Platform." },
  { vendor: "sap", type: "Integration", impact: "available", date: "2026-01-01", dateLabel: "2026",
    title: "SAP Concur Fusion adds Joule + Microsoft 365 integration",
    url: "https://erp.today/tag/sap-concur-fusion-2026/",
    blurb: "New AI agents automate expense workflows with expanded Amex and Visa partnerships." },

  // ---- ServiceNow ----
  { vendor: "servicenow", type: "Platform", impact: "available", date: "2026-01-01", dateLabel: "2026",
    title: "Now Assist shifts from chatbot to agentic enterprise",
    url: "https://www.servicenow.com/company/media/press-room.html",
    blurb: "ServiceNow leadership frames 2026 as \"the year of agentic collaboration,\" with AI agents that plan, decide, and execute multistep workflows." },
  { vendor: "servicenow", type: "Integration", impact: "available", date: "2026-08-06", dateLabel: "Aug",
    title: "Now Assist adds native Workday and SAP connectors",
    url: "https://www.servicenow.com/company/media/press-room.html",
    blurb: "Cross-system workflow agents can read and write HR and finance records directly." },
  { vendor: "servicenow", type: "Platform", impact: "announced", date: "2026-06-16", dateLabel: "Jun 16",
    title: "Automated guardrails and custom agent capabilities",
    url: "https://www.servicenow.com/company/media/press-room.html",
    blurb: "New governance tooling and custom agent capabilities that reason over enterprise data." },

  // ---- Oracle ----
  { vendor: "oracle", type: "Platform", impact: "available", date: "2026-01-01", dateLabel: "2026",
    title: "Oracle AI Database adds native vector search and RAG",
    url: "https://www.oracle.com/news/",
    blurb: "Vector search and retrieval-augmented generation are built directly into the Oracle Database engine." },
  { vendor: "oracle", type: "New feature", impact: "available", date: "2026-08-13", dateLabel: "Aug",
    title: "Fusion Apps AI agents extend to procurement",
    url: "https://www.oracle.com/news/",
    blurb: "Autonomous sourcing and requisition agents join the existing finance and HR agent lineup." },
  { vendor: "oracle", type: "Release notes", impact: "announced", date: "2026-09-01", dateLabel: "Sep 1",
    title: "OAC September 2026 update — new Workbook authoring",
    url: "https://www.oracle.com/news/",
    blurb: "Refreshed Data, Visualize, and Present tabs across Oracle Analytics Cloud's Workbook authoring experience." },

  // ---- Salesforce ----
  { vendor: "salesforce", type: "Platform", impact: "ga", date: "2025-06-23", dateLabel: "Jun '25 → 2026",
    title: "Agentforce 3 adds a Command Center and MCP interoperability",
    url: "https://www.salesforce.com/news/stories/video/top-news-from-agentforce-3-keynote/",
    blurb: "Agentforce 3 brought agent observability, MCP-based interoperability, and 100+ pre-built industry actions via AgentExchange — usage has since more than tripled.",
    featured: true },
  { vendor: "salesforce", type: "New feature", impact: "available", date: "2026-03-12", dateLabel: "Mar 12",
    title: "Agentforce Contact Center launches at Enterprise Connect",
    url: "https://www.salesforce.com/news/",
    blurb: "Native contact-center capabilities join CRM data and AI agents on one platform, including live voice handling." },
  { vendor: "salesforce", type: "Release notes", impact: "available", date: "2025-12-03", dateLabel: "Dec '25",
    title: "Agentforce surpasses 3.2 trillion tokens processed",
    url: "https://www.salesforce.com/news/press-releases/2025/12/03/fy26-q3-earnings/",
    blurb: "Salesforce's FY26 Q3 results cite Agentforce and Data 360 as key drivers of record revenue and remaining performance obligations." },

  // ---- Workday ----
  { vendor: "workday", type: "Event", impact: "coming", date: "2026-10-13", dateLabel: "Oct 13",
    title: "Workday Financial Analyst Day 2026",
    url: "https://www.workday.com/en-us/company/newsroom.html",
    blurb: "Workday's annual investor event — expect updates on AI agent adoption and the Illuminate platform." },
  { vendor: "workday", type: "Platform", impact: "available", date: "2026-03-26", dateLabel: "Mar 26",
    title: "A new wave of agentic AI arrives worldwide",
    url: "https://www.workday.com/en-us/company/newsroom.html",
    blurb: "Workday AI agents, Workday Data Cloud, and new developer tooling now available worldwide." },
  { vendor: "workday", type: "Integration", impact: "available", date: "2026-08-10", dateLabel: "Aug",
    title: "Illuminate agents add skills-coaching capabilities",
    url: "https://www.workday.com/en-us/company/newsroom.html",
    blurb: "Personalized learning agents recommend upskilling paths grounded in Workday Data Cloud." },

  // ---- Adobe ----
  { vendor: "adobe", type: "Platform", impact: "available", date: "2026-01-01", dateLabel: "2026",
    title: "Firefly and GenStudio expand enterprise campaign tooling",
    url: "https://news.adobe.com/",
    blurb: "Adobe continues building out commercially-safe generative media and cross-channel campaign agents for enterprise marketing teams." },
  { vendor: "adobe", type: "Governance", impact: "announced", date: "2026-09-01", dateLabel: "Sep",
    title: "C2PA content credentials expand across Creative and Document Cloud",
    url: "https://news.adobe.com/",
    blurb: "Adobe is gradually rolling out C2PA provenance metadata across its creative and document tools." },
  { vendor: "adobe", type: "New feature", impact: "available", date: "2026-06-01", dateLabel: "Jun",
    title: "Acrobat AI Assistant expands document-agent capabilities",
    url: "https://news.adobe.com/",
    blurb: "Document Cloud's AI assistant adds deeper summarization and cross-document analysis features." },

  // ---- Databricks ----
  { vendor: "databricks", type: "Platform", impact: "available", date: "2026-01-01", dateLabel: "2026",
    title: "Agent Bricks lets teams define agents in plain English",
    url: "https://www.databricks.com/company/newsroom",
    blurb: "Agent Bricks, Mosaic AI fine-tuning, and the Genie natural-language interface continue to anchor Databricks' AI push into 2026." },
  { vendor: "databricks", type: "Governance", impact: "available", date: "2026-01-01", dateLabel: "2026",
    title: "Unity Catalog extends lineage to agent actions",
    url: "https://www.databricks.com/company/newsroom",
    blurb: "Every action an agent takes against governed lakehouse data is traceable back to its originating prompt." },
  { vendor: "databricks", type: "Model release", impact: "available", date: "2026-08-06", dateLabel: "Aug",
    title: "Mosaic AI adds fine-tuning for open reasoning models",
    url: "https://www.databricks.com/company/newsroom",
    blurb: "Customers can fine-tune open reasoning models directly on governed lakehouse data without export." },

  // ---- Snowflake ----
  { vendor: "snowflake", type: "Platform", impact: "ga", date: "2026-06-12", dateLabel: "Jun",
    title: "Snowflake Summit 2026: Cortex Code (\"CoCo\") and the agentic control plane",
    url: "https://www.cdomagazine.tech/aiml/snowflake-launches-new-tools-to-help-enterprises-deploy-agentic-ai",
    blurb: "Snowflake pitched Cortex Code as an agentic coding/data-engineering partner and reaffirmed a $6B committed-spend agreement with AWS.",
    featured: true },
  { vendor: "snowflake", type: "New feature", impact: "available", date: "2026-04-21", dateLabel: "Apr 21",
    title: "Snowflake Intelligence expands as the agentic control plane",
    url: "https://www.cdomagazine.tech/aiml/snowflake-launches-new-tools-to-help-enterprises-deploy-agentic-ai",
    blurb: "Major upgrades position Snowflake Intelligence and Cortex Code as the governed control layer for enterprise agent deployments." },
  { vendor: "snowflake", type: "Model release", impact: "announced", date: "2026-03-18", dateLabel: "Mar 18",
    title: "Project SnowWork research preview",
    url: "https://www.snowflake.com/en/news/",
    blurb: "A research preview of a new autonomous enterprise AI platform built on Snowflake's governed data foundation." },

  // ---- Palantir ----
  { vendor: "palantir", type: "Platform", impact: "available", date: "2025-01-01", dateLabel: "2025 → 2026",
    title: "Agentic Foundry extends AIP to autonomous action",
    url: "https://www.palantir.com/newsroom/",
    blurb: "Agents built on Palantir's ontology don't just recommend actions — supply-chain rerouting, predictive maintenance, and risk flags now execute directly." },
  { vendor: "palantir", type: "Partnership", impact: "available", date: "2026-01-01", dateLabel: "2026",
    title: "Palantir expands industrial and government AIP deployments",
    url: "https://www.palantir.com/newsroom/",
    blurb: "New manufacturing, logistics, and public-sector customers adopt AIP for ontology-grounded decision agents." },
  { vendor: "palantir", type: "Governance", impact: "announced", date: "2026-01-01", dateLabel: "2026",
    title: "Palantir details agent-oversight requirements for government customers",
    url: "https://www.palantir.com/newsroom/",
    blurb: "New audit and human-in-the-loop requirements for agents operating in defense and public-sector deployments." },

  // ---- UiPath ----
  { vendor: "uipath", type: "Event", impact: "coming", date: "2026-10-01", dateLabel: "FUSION",
    title: "UiPath FUSION 2026",
    url: "https://www.uipath.com/newsroom",
    blurb: "UiPath's leadership is set to demo coding agents, an AI-native canvas, and agentic testing at its annual event." },
  { vendor: "uipath", type: "Platform", impact: "available", date: "2026-01-01", dateLabel: "2026",
    title: "Agentic Automation combines RPA with modern LLM agents",
    url: "https://www.uipath.com/newsroom",
    blurb: "UiPath's platform lets teams design RPA workflows and LLM agents side by side in one control plane." },
  { vendor: "uipath", type: "New feature", impact: "available", date: "2026-07-28", dateLabel: "Jul",
    title: "UiPath adds agentic testing for automations",
    url: "https://www.uipath.com/newsroom",
    blurb: "Automated regression testing extends to cover agent-driven, non-deterministic process steps." },

  // ---- CrowdStrike ----
  { vendor: "crowdstrike", type: "Platform", impact: "available", date: "2026-03-25", dateLabel: "Mar 25",
    title: "Charlotte AI AgentWorks Ecosystem launches at RSA 2026",
    url: "https://www.crowdstrike.com/en-us/press-releases/crowdstrike-launches-charlotte-ai-agentworks-ecosystem-for-building-secure-agents/",
    blurb: "A no-code platform for building secure agents launches with partners including AWS, Anthropic, NVIDIA, OpenAI, Accenture, Deloitte, and Salesforce.",
    featured: true },
  { vendor: "crowdstrike", type: "New feature", impact: "available", date: "2026-05-01", dateLabel: "May",
    title: "Charlotte AI ships seven specialized security agents",
    url: "https://www.crowdstrike.com/platform/charlotte-ai/",
    blurb: "Exposure prioritization, malware analysis, threat hunting, correlation-rule generation, and more roll out as a coordinated agent workforce." },
  { vendor: "crowdstrike", type: "Partnership", impact: "available", date: "2026-04-01", dateLabel: "Apr 1",
    title: "CrowdStrike deepens agentic SOC strategy with IBM and Intel",
    url: "https://www.crowdstrike.com/en-us/press-releases/",
    blurb: "Expanded collaboration integrates Charlotte AI with IBM's ATOM and brings Falcon capabilities to Intel AI PCs." },
];
