/* Enterprise AI Pulse — onesheets.js
   Per-vendor capability highlights and KPI meters. */

window.ONESHEETS = [
  {
    vendor: "openai",
    positioning: "Frontier-model factory racing toward DevDay 2026, with hardware ambitions alongside its core API and agent platform.",
    capabilities: [
      { icon: "model", title: "GPT-5 family", note: "Reasoning + tool-use flagship line." },
      { icon: "agent", title: "Agent Mode", note: "Autonomous multi-step tasks in ChatGPT." },
      { icon: "plug", title: "AgentKit + Responses API", note: "Build custom agents with tools + memory." },
      { icon: "lock", title: "Preparedness framework", note: "Cybersecurity capability thresholds for frontier models." },
      { icon: "chart", title: "Batch + fine-tuning", note: "Async discounts, RLHF tuning." },
      { icon: "code", title: "Codex in IDEs", note: "GitHub, Cursor, VS Code, JetBrains." },
    ],
    kpis: {
      maturity: { value: 96, note: "Consistent frontier releases, strongest tool ecosystem." },
      adoption: { value: 92, note: "70%+ of Fortune 500 have OpenAI in production." },
      pricing:  { value: 60, note: "API pay-as-you-go accessible; ChatGPT Enterprise premium." },
    },
  },
  {
    vendor: "chatgpt",
    positioning: "OpenAI's consumer + business chat layer — expanding into healthcare and education verticals in 2026.",
    capabilities: [
      { icon: "user", title: "Projects & memory", note: "Persistent context across conversations." },
      { icon: "office", title: "ChatGPT Business & Enterprise", note: "Shared workspaces, admin console." },
      { icon: "plug", title: "Connectors", note: "Slack, Notion, Google Drive, SharePoint." },
      { icon: "agent", title: "Agent mode", note: "Books, browses, and files on your behalf." },
      { icon: "chart", title: "ChatGPT for Clinicians", note: "Queries public healthcare datasets." },
      { icon: "lock", title: "Data controls", note: "Chats excluded from training by default in Business." },
    ],
    kpis: {
      maturity: { value: 90, note: "Iterates fastest of any consumer AI surface." },
      adoption: { value: 95, note: "The default AI entry point for most knowledge workers." },
      pricing:  { value: 40, note: "Free and Plus tiers keep entry pricing accessible." },
    },
  },
  {
    vendor: "claude",
    positioning: "Safety-first Claude platform — Opus 4.6's computer use and the June Fable/Mythos 5 launch anchor its 2026 enterprise push.",
    capabilities: [
      { icon: "model", title: "Opus 4.6 & Fable/Mythos 5", note: "Anthropic's frontier and Mythos-class tiers." },
      { icon: "eye", title: "Computer use", note: "Visually interprets and operates a desktop." },
      { icon: "agent", title: "Cowork & Tag", note: "Multi-step delegated work, Slack-native access." },
      { icon: "lock", title: "Constitutional AI", note: "Safety classifiers route high-risk queries away." },
      { icon: "plug", title: "MCP", note: "Open standard for connecting tools and data." },
      { icon: "office", title: "Claude for Excel/PPT/Word", note: "Native Office-suite agents." },
    ],
    kpis: {
      maturity: { value: 92, note: "Leading safety posture; frontier coding benchmarks." },
      adoption: { value: 78, note: "300,000+ business customers; enterprise accounts growing fast." },
      pricing:  { value: 65, note: "Premium API tier; Team/Enterprise plans for orgs." },
    },
  },
  {
    vendor: "perplexity",
    positioning: "Answer engine + Comet agentic browser, expanding on-device Hybrid Compute for privacy-sensitive work.",
    capabilities: [
      { icon: "search", title: "Answer engine", note: "Cited, real-time web answers." },
      { icon: "eye", title: "Comet browser", note: "Agentic browsing that acts on pages for you." },
      { icon: "agent", title: "Perplexity Computer", note: "Hybrid cloud/local task execution." },
      { icon: "chart", title: "Perplexity Finance", note: "Real-time quotes, filings, comparisons." },
      { icon: "lock", title: "On-device Hybrid Compute", note: "Sensitive steps run locally." },
      { icon: "plug", title: "Enterprise Pro", note: "SSO, admin controls for teams." },
    ],
    kpis: {
      maturity: { value: 80, note: "Strong in search-grounded and agentic browsing use cases." },
      adoption: { value: 65, note: "Widespread among knowledge workers, growing in enterprise." },
      pricing:  { value: 30, note: "Free tier plus accessible Pro subscription." },
    },
  },
  {
    vendor: "grok",
    positioning: "xAI's Grok 4 family, trained on the Colossus cluster, expanding developer API access and X-native agent integration.",
    capabilities: [
      { icon: "model", title: "Grok 4 family", note: "Frontier reasoning models on Colossus." },
      { icon: "agent", title: "X-native agents", note: "Always-on assistant for organization accounts." },
      { icon: "code", title: "Developer API", note: "Expanding enterprise access outside of X." },
      { icon: "eye", title: "Vision & multimodal", note: "Image and video understanding." },
      { icon: "chart", title: "Usage-based pricing", note: "Developer platform with tiered access." },
      { icon: "plug", title: "Third-party integrations", note: "Growing outside the X ecosystem." },
    ],
    kpis: {
      maturity: { value: 72, note: "Competitive frontier model, faster iteration than peers." },
      adoption: { value: 55, note: "Growing beyond X into standalone enterprise use." },
      pricing:  { value: 35, note: "Moderate API pricing relative to other frontier labs." },
    },
  },
  {
    vendor: "microsoft",
    positioning: "Copilot everywhere — Cowork reached GA in June, with agent tooling now spanning SharePoint, Studio, and Dynamics.",
    capabilities: [
      { icon: "office", title: "Microsoft 365 Copilot", note: "Embedded across Word, Excel, Teams, Outlook." },
      { icon: "agent", title: "Copilot Cowork (GA)", note: "Multi-model, multi-agent delegated work." },
      { icon: "model", title: "Azure AI Foundry", note: "Model catalog spanning OpenAI, Claude, and more." },
      { icon: "lock", title: "Purview governance", note: "Compliance and data-loss-prevention for agents." },
      { icon: "plug", title: "Dynamics 365 agents", note: "Sales, service, and finance copilots." },
      { icon: "code", title: "GitHub Copilot", note: "AI pair programming across the SDLC." },
    ],
    kpis: {
      maturity: { value: 96, note: "Deepest enterprise AI distribution of any vendor." },
      adoption: { value: 97, note: "Copilot embedded across nearly all Microsoft surfaces." },
      pricing:  { value: 72, note: "Per-seat Copilot licensing is a real budget line for IT." },
    },
  },
  {
    vendor: "google",
    positioning: "Gemini Enterprise Agent Platform (from Cloud Next) plus Gemini 3.5/Omni (from I/O) anchor Google's 2026 push.",
    capabilities: [
      { icon: "model", title: "Gemini 3.5 & Omni", note: "Coding- and agent-focused model family." },
      { icon: "office", title: "Gemini for Workspace", note: "Now bundled into Business & Enterprise pricing." },
      { icon: "agent", title: "Gemini Enterprise Agent Platform", note: "Conversational agent builder for large businesses." },
      { icon: "search", title: "Search grounding", note: "Real-time grounding via Google Search." },
      { icon: "lock", title: "DLP controls", note: "Admin controls over agent data access." },
      { icon: "chart", title: "AI Studio & Vertex AI", note: "Prototyping and production tooling for developers." },
    ],
    kpis: {
      maturity: { value: 94, note: "Rapid model cadence; strong multimodal and search grounding." },
      adoption: { value: 93, note: "Ubiquitous via Workspace, Android, and Search surfaces." },
      pricing:  { value: 58, note: "Tiered Gemini plans; Vertex AI usage-based pricing." },
    },
  },
  {
    vendor: "aws",
    positioning: "Bedrock AgentCore reached GA in June and expanded further at the August New York Summit — the neutral hosting layer for enterprise AI.",
    capabilities: [
      { icon: "plug", title: "Bedrock model marketplace", note: "Anthropic, Meta, OpenAI, Google, and Amazon Nova." },
      { icon: "agent", title: "AgentCore (GA)", note: "Managed runtime for long-running, production agents." },
      { icon: "lock", title: "Guardrails", note: "Content filtering and policy enforcement." },
      { icon: "chart", title: "Managed Knowledge Base", note: "Faster, governed RAG pipelines." },
      { icon: "model", title: "Amazon Nova", note: "Amazon's own multimodal model family." },
      { icon: "code", title: "Q Developer", note: "AI coding assistant across the AWS console." },
    ],
    kpis: {
      maturity: { value: 93, note: "Broadest model marketplace of any hyperscaler." },
      adoption: { value: 94, note: "Default hosting layer for many regulated enterprises." },
      pricing:  { value: 62, note: "Usage-based Bedrock pricing; premium for managed agent tooling." },
    },
  },
  {
    vendor: "nvidia",
    positioning: "AI factory stack — Nemotron reasoning models, NIM microservices, and Computex 2026's expanded agent infrastructure push.",
    capabilities: [
      { icon: "chart", title: "Blackwell & Rubin GPUs", note: "The compute layer under nearly every frontier model." },
      { icon: "plug", title: "NIM microservices", note: "Prepackaged, portable inference containers." },
      { icon: "model", title: "Nemotron models", note: "Open models tuned for agentic reasoning." },
      { icon: "agent", title: "NVIDIA AI Enterprise", note: "Full-stack software for production AI." },
      { icon: "code", title: "CUDA-X libraries", note: "The developer ecosystem moat." },
      { icon: "lock", title: "Confidential computing", note: "Hardware-level data protection for inference." },
    ],
    kpis: {
      maturity: { value: 98, note: "The infrastructure layer nearly every AI vendor builds on." },
      adoption: { value: 96, note: "De facto standard for AI training and inference hardware." },
      pricing:  { value: 92, note: "Premium hardware and software pricing at enterprise scale." },
    },
  },
  {
    vendor: "meta",
    positioning: "Llama open models under the new Superintelligence Labs org — open weights, deep vertical integration.",
    capabilities: [
      { icon: "model", title: "Llama 4 family", note: "Open-weight models widely used for fine-tuning." },
      { icon: "agent", title: "Superintelligence Labs", note: "Reorganized AI org built for faster execution." },
      { icon: "user", title: "Meta AI", note: "Assistant across WhatsApp, Messenger, Instagram." },
      { icon: "eye", title: "Reality Labs AI", note: "AI features across smart glasses and headsets." },
      { icon: "plug", title: "Llama API", note: "Hosted inference for open-weight models." },
      { icon: "chart", title: "Custom inference silicon", note: "In-house chip efforts to reduce serving cost." },
    ],
    kpis: {
      maturity: { value: 88, note: "Leading open-weight model family with strong fine-tuning ecosystem." },
      adoption: { value: 82, note: "Widely used as a base model across the open-source community." },
      pricing:  { value: 15, note: "Open weights keep self-hosted use highly accessible." },
    },
  },
  {
    vendor: "ibm",
    positioning: "watsonx + Granite — hybrid, governed AI for regulated enterprises, now integrating CrowdStrike's Charlotte AI into ATOM.",
    capabilities: [
      { icon: "agent", title: "watsonx Orchestrate", note: "Pre-built agents with compliance audit trails." },
      { icon: "model", title: "Granite model family", note: "Open enterprise models, multilingual variants." },
      { icon: "lock", title: "watsonx.governance", note: "Model risk management and audit tooling." },
      { icon: "plug", title: "ATOM + Charlotte AI", note: "Coordinated, machine-speed SOC response with CrowdStrike." },
      { icon: "chart", title: "watsonx.data", note: "Governed lakehouse for enterprise AI." },
      { icon: "office", title: "Consulting-led rollouts", note: "IBM Consulting implementation practice." },
    ],
    kpis: {
      maturity: { value: 74, note: "Strong in governance tooling, slower model cadence than peers." },
      adoption: { value: 70, note: "Concentrated in finance, government, and healthcare." },
      pricing:  { value: 58, note: "Enterprise licensing plus consulting-led implementation cost." },
    },
  },
  {
    vendor: "sap",
    positioning: "Sapphire 2026 unified BTP, Business Data Cloud, and AI Foundation into one Business AI Platform — Joule now orchestrates 224 agents.",
    capabilities: [
      { icon: "agent", title: "Joule Work", note: "Single workspace for assistants and action-taking agents." },
      { icon: "plug", title: "SAP AI Agent Hub", note: "Vendor-agnostic agent marketplace, GA Q3 2026." },
      { icon: "lock", title: "AI governance framework", note: "Guardrails and audit tooling for production agents." },
      { icon: "chart", title: "Business AI Platform", note: "BTP + Business Data Cloud + AI Foundation, unified." },
      { icon: "office", title: "224 AI agents / 51 Joule Assistants", note: "Across Finance, Supply Chain, HCM, Procurement, CX." },
      { icon: "model", title: "Knowledge Graph", note: "Semantic layer across 452K SAP tables." },
    ],
    kpis: {
      maturity: { value: 82, note: "Deep ERP-native agent integration, tightly scoped to SAP data." },
      adoption: { value: 88, note: "Standard across the large SAP installed base." },
      pricing:  { value: 88, note: "Enterprise-only licensing tied to core ERP contracts." },
    },
  },
  {
    vendor: "servicenow",
    positioning: "Now Assist's 2026 shift from chatbot to full agentic enterprise — agents that plan, decide, and execute multistep workflows.",
    capabilities: [
      { icon: "agent", title: "Agentic enterprise agents", note: "Plan, decide, and execute without constant prompting." },
      { icon: "plug", title: "Now Assist connectors", note: "Native links to Workday, SAP, and Salesforce." },
      { icon: "lock", title: "Automated guardrails", note: "Governance for agents reasoning over enterprise data." },
      { icon: "chart", title: "Workflow analytics", note: "Tracks agent impact on ticket resolution time." },
      { icon: "office", title: "IT Service Management AI", note: "The original ServiceNow use case, now agentic." },
      { icon: "user", title: "HR & Customer Service agents", note: "Extends beyond IT into shared services." },
    ],
    kpis: {
      maturity: { value: 78, note: "Strong workflow-automation heritage extended into agents." },
      adoption: { value: 72, note: "Widespread in IT service management, growing elsewhere." },
      pricing:  { value: 68, note: "Premium add-on pricing on top of core ITSM licenses." },
    },
  },
  {
    vendor: "oracle",
    positioning: "AI Database + Fusion Apps AI, tightly integrated with OCI GPU capacity — now extending agents into procurement.",
    capabilities: [
      { icon: "chart", title: "Oracle AI Database", note: "Vector search and RAG built into the database engine." },
      { icon: "agent", title: "Fusion Apps AI agents", note: "Finance, HR, and now procurement agents." },
      { icon: "plug", title: "OCI GPU capacity", note: "Zettascale training capacity for frontier labs." },
      { icon: "office", title: "OAC Workbook authoring", note: "Refreshed analytics authoring experience." },
      { icon: "lock", title: "Data residency controls", note: "Regional deployment options for regulated data." },
      { icon: "model", title: "Select AI", note: "Natural-language querying over Oracle databases." },
    ],
    kpis: {
      maturity: { value: 76, note: "Deep database-native AI, apps AI catching up to peers." },
      adoption: { value: 70, note: "Strong in the existing Oracle database and ERP base." },
      pricing:  { value: 66, note: "Premium OCI and Fusion Apps AI licensing." },
    },
  },
  {
    vendor: "salesforce",
    positioning: "Agentforce 3's Command Center and MCP interoperability took usage from pilot to production — 3.2 trillion+ tokens processed.",
    capabilities: [
      { icon: "agent", title: "Agentforce 3", note: "Command Center for agent observability at scale." },
      { icon: "plug", title: "MCP interoperability", note: "Secure agent connections via Model Context Protocol." },
      { icon: "user", title: "Agentforce Contact Center", note: "End-to-end live call handling." },
      { icon: "chart", title: "AgentExchange", note: "100+ pre-built industry actions." },
      { icon: "lock", title: "Trust Layer", note: "Data masking and audit trails for agent actions." },
      { icon: "office", title: "Data Cloud grounding", note: "Real-time customer data grounds every agent." },
    ],
    kpis: {
      maturity: { value: 88, note: "Agentforce is in production at scale, not just pilots." },
      adoption: { value: 90, note: "Ubiquitous across the existing Salesforce customer base." },
      pricing:  { value: 74, note: "Premium per-conversation and per-seat Agentforce pricing." },
    },
  },
  {
    vendor: "workday",
    positioning: "AI-native HR + Finance agents via the Illuminate platform, with a global rollout completed in March 2026.",
    capabilities: [
      { icon: "agent", title: "Illuminate agents", note: "Recruiting, payroll, and finance close agents." },
      { icon: "user", title: "Skills-coaching agents", note: "Personalized upskilling recommendations." },
      { icon: "chart", title: "Workday Data Cloud", note: "Unified HR and financial data for agent grounding." },
      { icon: "plug", title: "Developer tooling", note: "Extensibility platform for custom agents." },
      { icon: "office", title: "Financial close agents", note: "Automates reconciliation and reporting tasks." },
      { icon: "lock", title: "Audit-ready agent logs", note: "Tracks agent actions against HR/finance records." },
    ],
    kpis: {
      maturity: { value: 72, note: "Solid agentic rollout across core HR and finance modules." },
      adoption: { value: 68, note: "Widespread in the existing Workday customer base." },
      pricing:  { value: 60, note: "Premium add-on pricing layered on core HCM/Financials." },
    },
  },
  {
    vendor: "adobe",
    positioning: "Firefly + GenStudio — commercially safe generative media, now adding C2PA provenance metadata across Creative and Document Cloud.",
    capabilities: [
      { icon: "eye", title: "Firefly generative models", note: "Trained for commercially safe output." },
      { icon: "lock", title: "C2PA content credentials", note: "Provenance metadata across Creative and Document Cloud." },
      { icon: "chart", title: "Brand-guideline enforcement", note: "Automatic checks against brand and legal rules." },
      { icon: "agent", title: "GenStudio campaign agents", note: "Plans and routes creative across channels." },
      { icon: "office", title: "Acrobat AI Assistant", note: "Document summarization and cross-document analysis." },
      { icon: "plug", title: "Firefly Services API", note: "Programmatic access for enterprise workflows." },
    ],
    kpis: {
      maturity: { value: 86, note: "Leading commercially safe generative media offering." },
      adoption: { value: 80, note: "Widespread among marketing and creative teams." },
      pricing:  { value: 62, note: "Premium tiers layered on existing Creative Cloud licenses." },
    },
  },
  {
    vendor: "databricks",
    positioning: "Mosaic AI + Agent Bricks — unified lakehouse for governed enterprise AI, with lineage now extending to agent actions.",
    capabilities: [
      { icon: "agent", title: "Agent Bricks", note: "Define agents in plain English; automated evaluation." },
      { icon: "model", title: "Mosaic AI fine-tuning", note: "Tune open reasoning models on lakehouse data." },
      { icon: "lock", title: "Unity Catalog lineage", note: "Tracks every agent action back to its data source." },
      { icon: "chart", title: "Genie", note: "Natural-language interface for analysts, no SQL required." },
      { icon: "plug", title: "Model Serving", note: "Unified endpoint for open and proprietary models." },
      { icon: "code", title: "Databricks Assistant", note: "AI pair-programmer inside notebooks." },
    ],
    kpis: {
      maturity: { value: 85, note: "Strong lakehouse-native agent tooling, fast iteration." },
      adoption: { value: 76, note: "Widespread among data and ML engineering teams." },
      pricing:  { value: 64, note: "Consumption-based pricing scales with usage." },
    },
  },
  {
    vendor: "snowflake",
    positioning: "Cortex Code (\"CoCo\") and Snowflake Intelligence position it as the agentic control plane — reaffirmed with a $6B AWS spend deal.",
    capabilities: [
      { icon: "chart", title: "Snowflake Intelligence", note: "Natural-language agent builder over governed data." },
      { icon: "code", title: "Cortex Code (\"CoCo\")", note: "Agentic coding & data-engineering partner." },
      { icon: "lock", title: "Zero-copy governance", note: "Agents query data without it ever leaving Snowflake." },
      { icon: "agent", title: "Cortex Agents", note: "Structured + unstructured data agents in one workflow." },
      { icon: "model", title: "Project SnowWork", note: "Research preview of an autonomous enterprise AI platform." },
      { icon: "plug", title: "Iceberg v3 + Datastream", note: "Open, real-time data interoperability." },
    ],
    kpis: {
      maturity: { value: 80, note: "Strong governed-data AI story, growing agent tooling." },
      adoption: { value: 74, note: "Widespread among data warehouse and analytics teams." },
      pricing:  { value: 60, note: "Consumption-based Cortex pricing on top of warehouse costs." },
    },
  },
  {
    vendor: "palantir",
    positioning: "AIP's Agentic Foundry moves from recommending actions to taking them — the ontology-driven agent OS for defense and industrials.",
    capabilities: [
      { icon: "agent", title: "Agentic Foundry", note: "Agents execute supply-chain, maintenance, and risk actions." },
      { icon: "lock", title: "Agent-oversight framework", note: "Human-in-the-loop controls for sensitive deployments." },
      { icon: "chart", title: "Foundry ontology", note: "The data model underlying every AIP agent." },
      { icon: "plug", title: "Industrial partnerships", note: "Manufacturing and logistics decision agents." },
      { icon: "office", title: "Government & defense focus", note: "Deepest deployment base in regulated public sector." },
      { icon: "model", title: "Model-agnostic orchestration", note: "Routes across commercial and open models." },
    ],
    kpis: {
      maturity: { value: 88, note: "Mature ontology-driven agent orchestration, proven at scale." },
      adoption: { value: 60, note: "Concentrated in defense, government, and select industrials." },
      pricing:  { value: 95, note: "High-touch, enterprise-only contracts with long deployment cycles." },
    },
  },
  {
    vendor: "uipath",
    positioning: "Agentic Automation — combining RPA depth with modern LLM agents, heading into FUSION 2026 with a new AI-native canvas.",
    capabilities: [
      { icon: "agent", title: "AI-native process canvas", note: "Design RPA and LLM agents side by side." },
      { icon: "chart", title: "Agentic testing", note: "Regression testing for non-deterministic agent steps." },
      { icon: "plug", title: "Orchestrator", note: "Central control plane for bots and agents." },
      { icon: "model", title: "Autopilot", note: "AI-assisted workflow authoring." },
      { icon: "lock", title: "Governance & audit", note: "Compliance tooling carried over from RPA heritage." },
      { icon: "code", title: "Agent Builder", note: "Low-code environment for custom agents." },
    ],
    kpis: {
      maturity: { value: 76, note: "Deep RPA heritage now extended with modern agent tooling." },
      adoption: { value: 70, note: "Widespread among existing RPA customers modernizing to agents." },
      pricing:  { value: 58, note: "Premium licensing layered on existing automation contracts." },
    },
  },
  {
    vendor: "crowdstrike",
    positioning: "Charlotte AI's AgentWorks Ecosystem (launched at RSA 2026) turns Falcon into the foundation other vendors' agents run on.",
    capabilities: [
      { icon: "agent", title: "Charlotte AI (7 agents)", note: "Exposure prioritization, malware analysis, threat hunting." },
      { icon: "lock", title: "Falcon Guardian", note: "Runtime protection and guardrails for AI agents." },
      { icon: "plug", title: "AgentWorks Ecosystem", note: "No-code agent builder with AWS, Anthropic, NVIDIA, OpenAI." },
      { icon: "chart", title: "Charlotte Agentic SOAR", note: "Orchestrates the agentic SOC value chain." },
      { icon: "eye", title: "Threat detection", note: "Endpoint, identity, and cloud telemetry in one platform." },
      { icon: "user", title: "SOC analyst co-pilot", note: "Human-reviewed AI recommendations, not full autonomy." },
    ],
    kpis: {
      maturity: { value: 78, note: "First security vendor to ship a full agentic ecosystem, not just a co-pilot." },
      adoption: { value: 72, note: "Widespread among existing Falcon platform customers." },
      pricing:  { value: 65, note: "Premium add-on modules on top of core Falcon licensing." },
    },
  },
];
